# ============================================
# Xnix 系统服务配置
# ============================================

# --- 服务发现定义 ---

[handle.ramfs_ep]
type = endpoint

[handle.serial]
type = endpoint

[handle.serial_in]
type = endpoint

[handle.kbd_ep]
type = endpoint

[handle.tty0]
type = endpoint

[handle.tty1]
type = endpoint

[handle.vfs_ep]
type = endpoint

[handle.fatfs_ep]
type = endpoint

[handle.fb_mem]
type = inherit

[handle.vga_mem]
type = inherit

[handle.vga_ep]
type = endpoint

[handle.fbcon_ep]
type = endpoint

[handle.boot.system]
type = inherit

[handle.fatfs_ata_ep]
type = endpoint

[handle.fatfs_ata1_ep]
type = endpoint

[handle.devfs_ep]
type = endpoint

[handle.sudo_ep]
type = endpoint

[handle.ws_ep]
type = endpoint

[handle.syslog_ep]
type = endpoint

[handle.mouse_ep]
type = endpoint

# --- 核心服务 (ramfs 加载) ---

[service.seriald]
path = ramfs:///sbin/seriald.elf
provides = serial serial_in

[service.syslogd]
path = ramfs:///sbin/syslogd.elf
after = seriald
provides = syslog_ep

[service.kbd]
path = ramfs:///sbin/kbd.elf
after = seriald
handles = kbd_ep

[service.moused]
path = ramfs:///sbin/moused.elf
after = seriald kbd
handles = mouse_ep

[service.vfsserver]
path = ramfs:///sbin/vfsserver.elf
after = seriald
provides = vfs_ep
handles = serial

[service.fatfsd]
path = ramfs:///sbin/fatfsd.elf
after = seriald vfsserver
ready = vfsserver
provides = fatfs_ep
handles = serial boot.system
mount = /

[service.fatfsd_ata]
path = /sbin/fatfsd.elf
args = --ata
after = seriald vfsserver fatfsd
ready = vfsserver fatfsd
provides = fatfs_ata_ep
handles = serial devfs_ep
mount = /mnt/sda1

[service.fatfsd_ata1]
path = /sbin/fatfsd.elf
args = --ata --drive 1
after = seriald vfsserver fatfsd
ready = vfsserver fatfsd
provides = fatfs_ata1_ep
handles = serial devfs_ep
mount = /mnt/sdb1

[service.devfsd]
path = ramfs:///sbin/devfsd.elf
after = seriald vfsserver fatfsd
ready = vfsserver fatfsd
provides = devfs_ep
handles = serial
mount = /dev

[service.wsd]
path = ramfs:///sbin/wsd.elf
after = seriald kbd moused
provides = ws_ep
handles = fb_mem serial kbd_ep mouse_ep ws_ep

[service.fbcond]
path = ramfs:///sbin/fbcond.elf
after = seriald
provides = fbcon_ep
handles = fb_mem

[service.termd]
path = ramfs:///sbin/termd.elf
after = seriald kbd fbcond devfsd
provides = tty0 tty1
wants = devfs_ep
handles = serial serial_in kbd_ep fbcon_ep

[service.klogd]
path = ramfs:///sbin/klogd.elf
after = termd
ready = termd
wants = tty1

# --- 用户服务 (VFS 加载) ---

# [service.shell] — 暂停排查: 排除 tty0 干扰
# stdio = tty0

[service.shell_serial]
path = /bin/shell.elf
args = --tty=tty1 --svc=shell_serial
after = seriald vfsserver fatfsd termd klogd
ready = termd fatfsd
requires = vfs_ep tty1
wants = sudo_ep ws_ep
stdio = tty1
respawn = true

[service.sudod]
path = /bin/sudod.elf
after = vfsserver fatfsd termd
ready = fatfsd
provides = sudo_ep
handles = serial vfs_ep
respawn = true
